### PR TITLE
fix: enable loading images from the same webSource

### LINKED ISSUE #117: Cannot load image twice
Reproduction:
- Go to https://pixelium.zakodium.com/
- Load cells.png
- Close cells.png
- Load cells.png => image is not loaded

### PR DESCRIPTION
**Pull request by moonayyur**
closes #117

### CODE REVIEW

**Review by stropitek — COMMENTED** [review]
As discusesd, the webSource prop of Pixelium is a hack to have access to pixelium's reducer.

My advice is to separate `Pixelium` into 2 components:
- `PixeliumProvider` which contains the various providers needed by the pixelium UI.
- `PixeliumApp` with the pixelium UI

This way the sidebar in between can directly load files into pixelium's state.

File: src/components/context/WebSourceContext.tsx [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+  webSource: WebSource | undefined;
+  setWebSource: (value: WebSource | undefined) => void;
+}
+
+const WebSourceContext = createContext<WebSourceContextProps | undefined>(
+  undefined,
+);
+
+export function WebSourceProvider({ children }) {
+  const [webSource, setWebSource] = useState<WebSource | undefined>();
```
Comment (stropitek) [inline src/components/context/WebSourceContext.tsx:14]: I don't understand the role of this context and of this state.

Isn't this state not needed anymore? Can't you just remove this context and the `AutoLoader` component and call `handleWebSource` directly in the sidebar?

**Review by stropitek — APPROVED** [review]
